# Build pipeline
# More documentation at:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo curl -sSL https://get.haskellstack.org/ | sh
  displayName: 'Install stack'


