# Build pipeline
# More documentation at:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: stack upgrade
  displayName: 'Prepare stack'

- script: stack build
  displayName: 'Build the loft package'

