# Build pipeline
# More documentation at:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

  - bash: stack build
    displayName: 'Build the loft package'

  - script: stack test
    displayName: 'Run the tests'
