# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get update
    sudo apt-get install haskell-platform
    cabal update
    cabal configure
    cabal install --only-dependencies
  displayName: 'Prepare cabal'

- script: |
    cabal build
  displayName: 'Build the package'
