name:                loft
version:             0.1.0.0
github:              "WilliamHPNielsen/loft-fitness"
license:             BSD3
author:              "William H.P. Nielsen"
maintainer:          "whpn@mailbox.org"
copyright:           "2019 William H.P. Nielsen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/WilliamHPNielsen/loft-fitness#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  loft-exe:
    main:                main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - loft

tests:
  loft-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - loft
